### ISSUE TITLE
申请不了应用账户, 链接无效

### ISSUE THREAD

**Issue by acfasj** [redhome/api.hdu.edu.cn#1]
> WARNING: 不要在 Issue 中包含任何密钥信息

**Comment by 21emerald** [comment]
**申请应用帐户** 是没有开放的功能，我们希望可以和其他多数API一样让开发者自由申请应用、把数据的授权交给用户。

但由于学校的特殊性质，数据的使用需要更多的考量，并且是希望数据的使用都在校内的，以此来尽量保证数据的安全。

如要使用API，现**需要联系网络中心的老师来申请应用**。

你可能需要**说明使用人、使用场景和意图等**。

**Comment by XGHeaven** [comment]
联系方式在页面下方写着。
地址在 3 教 617 。

**Comment by acfasj** [comment]
好，感谢回复

**Comment by XGHeaven** [comment]
@acfasj close 掉吧
